"""IDA Pro headless decompiler fallback manager."""
from __future__ import annotations

import os
from pathlib import Path
import tempfile
import yaml

from re_agent.utils.process import run_cmd_split


class IDAFallbackManager:
    """Manages on-demand headless decompilation via IDA Pro Hex-Rays."""

    def __init__(self, ida_bin: str | None = None, timeout_s: int = 120) -> None:
        self.ida_bin = ida_bin
        self.timeout_s = timeout_s

    def get_idb_path(self, repo_root: Path) -> Path:
        """Resolve the target .i64 database path from the active config."""
        bridge_yaml = repo_root / "ghidra-bridge.yaml"
        if not bridge_yaml.exists():
            # Fallback to default
            return repo_root / "IDA Files" / "BURNOUT_X360_ARTIST.XEX.i64"

        try:
            with open(bridge_yaml, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f)
            prog = data.get("ghidra", {}).get("program_name", "")
            if "PS3" in prog or prog.lower().endswith(".elf"):
                return repo_root / "IDA Files" / "Burnout_External_PS3.ELF.i64"
        except Exception as e:
            print(f"[IDA-FALLBACK] Warning: Failed to parse ghidra-bridge.yaml: {e}")

        return repo_root / "IDA Files" / "BURNOUT_X360_ARTIST.XEX.i64"

    def decompile(self, address: str) -> str | None:
        """Decompile the given function address headlessly using IDA Pro.

        Returns the pseudocode string, or None if it failed.
        """
        repo_root = Path.cwd()
        ida_executable = self.ida_bin

        if not ida_executable:
            # Fallback default if not configured
            ida_executable = r"C:\Program Files\IDA Pro 9.0\idat64.exe"

        if not os.path.exists(ida_executable) and not any(
            os.path.exists(os.path.join(p, os.path.basename(ida_executable)))
            for p in os.environ.get("PATH", "").split(os.pathsep)
        ):
            print(f"[IDA-FALLBACK] Error: IDA executable not found: {ida_executable}")
            return None

        idb_path = self.get_idb_path(repo_root)
        if not idb_path.exists():
            print(f"[IDA-FALLBACK] Error: IDA database not found: {idb_path}")
            return None

        script_path = repo_root / "tools" / "ida_decompile.py"
        if not script_path.exists():
            print(f"[IDA-FALLBACK] Error: IDAPython script not found: {script_path}")
            return None

        # Prepare a temporary file to receive the pseudocode
        with tempfile.NamedTemporaryFile(suffix=".cpp", delete=False) as tmp:
            temp_out_path = Path(tmp.name)

        try:
            # Set environment variables for the script to pick up
            os.environ["IDA_DECOMPILE_ADDR"] = address
            os.environ["IDA_DECOMPILE_OUT"] = str(temp_out_path)

            print(f"[IDA-FALLBACK] Running headless IDA Pro on {idb_path.name} for 0x{address}...")

            # command structure for headless IDA
            # idat64 -A -S"script.py" "file.i64"
            args = [
                ida_executable,
                "-A",
                f"-S{script_path}",
                str(idb_path),
            ]

            rc, stdout, stderr = run_cmd_split(args, timeout_s=self.timeout_s)

            if rc != 0:
                print(f"[IDA-FALLBACK] Headless IDA failed (exit {rc})")
                print(f"Stdout:\n{stdout}")
                print(f"Stderr:\n{stderr}")
                return None

            if temp_out_path.exists():
                pseudocode = temp_out_path.read_text(encoding="utf-8")
                return pseudocode
            else:
                print("[IDA-FALLBACK] Error: Output file was not generated by IDA.")
                return None

        finally:
            # Clean up temporary file and environment variables
            if temp_out_path.exists():
                try:
                    temp_out_path.unlink()
                except OSError:
                    pass
            os.environ.pop("IDA_DECOMPILE_ADDR", None)
            os.environ.pop("IDA_DECOMPILE_OUT", None)
